server:
  port: 9002

spring:
  application:
    #name: nacos-payment-provider
    name: nacos-payment-abc

  cloud:
    nacos:
      discovery:
        #server-addr: localhost:8848
        server-addr: 116.62.14.29:80

management:
  endpoints:
    web:
      exposure:
        include: '*'

