server:
  port: 2003

spring:
  application:
    name: seata-account-service
  cloud:
    alibaba:
      seata:
        tx-service-group: my_test_tx_group
    nacos:
      discovery:
        server-addr: 116.62.14.29:80
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://116.62.14.29:3306/seata_account
    username: root
    password: root

  main:
    allow-bean-definition-overriding: true #解决feign名称冲突

feign:
  hystrix:
    enabled: false

logging:
  level:
    io:
      seata: info




