server:
  port: 2001

spring:
  application:
    name: seata-order-service
  cloud:
    alibaba:
      seata:
        tx-service-group: my_test_tx_group #查看seata中config.txt
    nacos:
      discovery:
        server-addr: 116.62.14.29:80

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://116.62.14.29:3306/seata_order?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&serverTimezone=UTC
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-active: 20
      min-idle: 10
      initial-size: 2

feign:
  hystrix:
    enabled: false


logging:
  level:
    io:
      seata: info
